export interface DateIdea {
  id: string
  title: string
  initiallyCompleted?: boolean
  custom?: boolean
}

export const dateIdeas: DateIdea[] = [
  { id: 'tarde-deportiva', title: 'Una tarde deportiva', initiallyCompleted: true },
  { id: 'cine', title: 'Ir al cine' },
  { id: 'karts', title: 'Ir a karts' },
  { id: 'cocinar-juntos', title: 'Cocinar juntos' },
  { id: 'cena-romantica', title: 'Una cena romántica', initiallyCompleted: true },
  { id: 'helado-parque', title: 'Un heladito en el parque' },
  { id: 'picnic', title: 'Hacer un picnic' },
  { id: 'hamburguesas', title: 'Una noche de hamburguesas', initiallyCompleted: true },
  { id: 'parque', title: 'Ir a un parque' },
  { id: 'estadio', title: 'Ir a un estadio' },
  { id: 'restaurante-elegante', title: 'Cenar en un restaurante elegante', initiallyCompleted: true },
  { id: 'karaoke', title: 'Una noche de karaoke' },
  { id: 'pueblito', title: 'Pasear por un pueblito' },
  { id: 'parapente', title: 'Volar en parapente' },
  { id: 'museo', title: 'Ir a un museo' },
  { id: 'lancha', title: 'Pasear en una lancha' },
  { id: 'comida-favorita', title: 'Preparar nuestra comida favorita en casa' },
  { id: 'comedia', title: 'Ir a un show de comedia' },
  { id: 'rompecabezas', title: 'Armar un rompecabezas' },
  { id: 'piscina-toboganes', title: 'Una tarde de piscina y toboganes' },
  { id: 'postre', title: 'Preparar un postre' },
  { id: 'planetario', title: 'Ir a un planetario' },
  { id: 'buggy', title: 'Dar un paseo en buggy' },
  { id: 'acuario', title: 'Visitar un acuario' },
  { id: 'pintar-cuadro', title: 'Pintar un cuadro' },
  { id: 'bucear', title: 'Ir a bucear' },
  { id: 'patinar', title: 'Ir a patinar', initiallyCompleted: true },
  { id: 'bicicleta', title: 'Dar un paseo en bicicleta' },
  { id: 'galletas', title: 'Hacer galletas' },
  { id: 'bolos', title: 'Ir a jugar bolos' },
  { id: 'playa', title: 'Ir a la playa' },
  { id: 'feria', title: 'Ir a una feria' },
  { id: 'concierto', title: 'Ir a un concierto', initiallyCompleted: true },
  { id: 'peluche-maquina', title: 'Sacar un peluche de una máquina' },
  { id: 'mirador', title: 'Ir a un mirador', initiallyCompleted: true },
  { id: 'tacos', title: 'Preparar tacos' },
  { id: 'zoologico', title: 'Ir a un zoológico' },
  { id: 'parque-diversiones', title: 'Ir a un parque de diversiones' },
  { id: 'compras', title: 'Ir de compras' },
  { id: 'amigos', title: 'Salir con amigos' },
  { id: 'kayak', title: 'Remar en kayak', initiallyCompleted: true },
  { id: 'helado-casa', title: 'Hacer helado en casa' },
  { id: 'tour', title: 'Viajar en un tour' },
  { id: 'avion', title: 'Viajar en avión' },
  { id: 'circo', title: 'Ir a un circo', initiallyCompleted: true },
  { id: 'paseo-familiar', title: 'Dar un paseo familiar' },
  { id: 'fiesta', title: 'Ir a una fiesta' },
  { id: 'pueblito-magico', title: 'Ir a un pueblito mágico', initiallyCompleted: true },
  { id: 'pescar', title: 'Ir a pescar' },
  { id: 'cena-familiar', title: 'Tener una cena familiar' },
  { id: 'cena-especial', title: 'Preparar una cena especial' },
  { id: 'teatro', title: 'Ir a ver teatro' },
  { id: 'salir-pais', title: 'Salir del país' },
  { id: 'manilla-juego', title: 'Tener una manilla de juego juntos' },
  { id: 'boda', title: 'Ir a una boda' },
  { id: 'buffet', title: 'Ir a un buffet' },
  { id: 'cascada', title: 'Ir a una cascada', initiallyCompleted: true },
  { id: 'ahorro', title: 'Iniciar un ahorro juntos' },
  { id: 'disfraces-fiesta', title: 'Ir a una fiesta de disfraces' },
  { id: 'sushi', title: 'Ir a una barra libre de sushi' },
  { id: 'crear-receta', title: 'Crear una receta' },
  { id: 'pizza-casa', title: 'Pedir pizza en casa' },
  { id: 'acampar', title: 'Ir a acampar', initiallyCompleted: true },
  { id: 'juegos-mesa', title: 'Jugar juegos de mesa' },
  { id: 'pedir-dulces', title: 'Ir a pedir dulces' },
  { id: 'deseo-globo', title: 'Escribir un deseo en un globo' },
  { id: 'lluvia', title: 'Caminar bajo la lluvia' },
  { id: 'sesion-fotos', title: 'Hacer una sesión de fotos' },
  { id: 'amanecer', title: 'Ver un amanecer' },
  { id: 'manualidad', title: 'Hacer una manualidad' },
  { id: 'pelicula-emotiva', title: 'Ver una película súper emotiva' },
  { id: 'caminata-ecologica', title: 'Hacer una caminata ecológica', initiallyCompleted: true },
  { id: 'desayuno-cama', title: 'Preparar el desayuno en la cama' },
  { id: 'fogata', title: 'Hacer una fogata', initiallyCompleted: true },
  { id: 'serie-completa', title: 'Ver una serie completa' },
  { id: 'mascotas', title: 'Pasear con nuestras mascotas' },
  { id: 'mismo-libro', title: 'Leer el mismo libro' },
  { id: 'cita-tematica', title: 'Hacer una cita temática' },
  { id: 'origami-almohadas', title: 'Hacer origami y una guerra de almohadas' },
  { id: 'pintar-pared', title: 'Pintar una pared' },
  { id: 'pijamada', title: 'Hacer una pijamada' },
  { id: 'asado', title: 'Hacer un asado' },
  { id: 'mueble', title: 'Armar un mueble', initiallyCompleted: true },
  { id: 'plantita', title: 'Cultivar una plantita' },
  { id: 'cometas', title: 'Volar cometas', initiallyCompleted: true },
  { id: 'lego', title: 'Armar un LEGO' },
  { id: 'spa', title: 'Ir a un spa' },
  { id: 'vestidos-combinando', title: 'Salir vestidos combinando' },
  { id: 'escapada-romantica', title: 'Hacer una escapada romántica', initiallyCompleted: true },
  { id: 'documental', title: 'Ver un documental' },
  { id: 'videojuegos', title: 'Jugar videojuegos' },
  { id: 'disfraz-pareja', title: 'Usar un disfraz en pareja' },
  { id: 'estudiar-juntos', title: 'Estudiar algo juntos' },
  { id: 'cuatrimotos', title: 'Dar un paseo en cuatrimotos' },
  { id: 'cita-libre-1', title: '', custom: true },
  { id: 'cita-libre-2', title: '', custom: true },
  { id: 'cita-libre-3', title: '', custom: true },
  { id: 'cita-libre-4', title: '', custom: true },
  { id: 'cita-libre-5', title: '', custom: true },
  { id: 'cita-libre-6', title: '', custom: true }
]
